# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.10648876 0.51319238 0.70175381 ... 0.43581988 0.00314594 0.84292753]
 [0.46182749 0.7302217  0.28542403 ... 0.91384914 0.09278792 0.66182865]
 [0.14119122 0.23561978 0.69128207 ... 0.17271654 0.58570006 0.51768802]
 ...
 [0.99256832 0.83291877 0.2989394  ... 0.72475904 0.80909492 0.29301702]
 [0.50845255 0.33529042 0.11271792 ... 0.1129312  0.03701606 0.23584171]
 [0.60726485 0.58514306 0.46938781 ... 0.91067845 0.33315848 0.04800045]]
[[9.09787315e-01 8.24704216e-02 1.44393122e-01 ... 9.53564399e-01
  6.56664503e-04 6.56928988e-01]
 [4.49255885e-01 5.82140408e-01 9.19859510e-01 ... 3.42756545e-01
  2.08774789e-01 6.68379132e-01]
 [5.80220190e-01 3.63588579e-01 4.48232460e-01 ... 5.63674880e-01
  9.09424413e-01 5.05185956e-01]
 ...
 [7.00727851e-01 1.92523094e-01 4.23607722e-01 ... 7.01153576e-02
  7.58259379e-01 4.47250233e-01]
 [4.52392285e-01 7.22306019e-01 5.97811236e-01 ... 5.98946525e-01
  5.5

Без использования numpy

In [3]:
def mult(a, b):
    result = [[0 for x in range(len(a))] for y in range(len(b[0]))]
    for i in range(len(a)):
      for j in range(len(b[0])):
        for k in range(len(b)):
          result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [4]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 693 ms, sys: 2.9 ms, total: 696 ms
Wall time: 697 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.79 ms, sys: 3.2 ms, total: 4.99 ms
Wall time: 8.33 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5091927707544528e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.68586676 0.27233495 0.21010559] [0.85243724 0.58275294 0.71022931]


In [15]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [17]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [18]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 18 µs, sys: 3 µs, total: 21 µs
Wall time: 24.6 µs
CPU times: user 77 µs, sys: 0 ns, total: 77 µs
Wall time: 63.9 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Значительная часть логики numpy написана на C, поэтому выполнение векторных операций происходит на порядок быстрее.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [40]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  main_diag = np.diag(a).tolist()
  flipped_matrix = np.fliplr(a)
  ex_diag = np.diag(flipped_matrix).tolist()
  *res, = filter(lambda x: int(x) % 2 == 0, (main_diag+ex_diag))
  return sum(res)

In [43]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 8, 9, 7, 9],
       [7, 2, 5, 2, 4],
       [3, 9, 3, 2, 6],
       [6, 5, 4, 4, 5],
       [7, 7, 1, 7, 5]])

In [44]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 61 µs, sys: 9 µs, total: 70 µs
Wall time: 74.1 µs


14

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [75]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    n = A.shape[1]
    cumsum = np.cumsum(A, axis=1)
    k_values = np.arange(1, n+1).reshape(1, n)
    return cumsum / k_values

In [76]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = np.random.uniform(0, 1, size = (10**3, 5))
A

array([[0.800749  , 0.59110094, 0.86906876, 0.47775622, 0.1801412 ],
       [0.18458247, 0.42714369, 0.84754633, 0.61482271, 0.2432793 ],
       [0.98686684, 0.45668206, 0.98299861, 0.13398241, 0.45301649],
       ...,
       [0.25984181, 0.50302624, 0.0450441 , 0.52114222, 0.34948478],
       [0.60086292, 0.93598736, 0.51030828, 0.81204386, 0.05367313],
       [0.48646781, 0.93568385, 0.40795331, 0.36573539, 0.47825373]])

In [77]:
%time S2 = np_sec_av(A)
S2

CPU times: user 185 µs, sys: 0 ns, total: 185 µs
Wall time: 193 µs


array([[0.800749  , 0.69592497, 0.75363957, 0.68466873, 0.58376322],
       [0.18458247, 0.30586308, 0.48642416, 0.5185238 , 0.4634749 ],
       [0.98686684, 0.72177445, 0.80884917, 0.64013248, 0.60270928],
       ...,
       [0.25984181, 0.38143402, 0.26930405, 0.33226359, 0.33570783],
       [0.60086292, 0.76842514, 0.68238619, 0.71480061, 0.58257511],
       [0.48646781, 0.71107583, 0.61003499, 0.54896009, 0.53481882]])

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [115]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
  flat = a.T.flatten()
  switches = np.nonzero(np.append(flat, 0) != np.append(0, flat))[0]
  elements = [a[i] for i in switches[0:-1]]
  rle_arr = (np.append(switches, switches[-1]) - np.append(0, switches))[1:-1]
  return np.array(elements), np.array(rle_arr)


In [117]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time el, x = np_encode(X)
el, x

CPU times: user 207 µs, sys: 0 ns, total: 207 µs
Wall time: 212 µs


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [150]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    indexes = np.array([int(i) for i in range(len(X))])
    np_arr = np.where(indexes % 2 == 0, X[indexes]**3, a)
    np_arr = np.flip(np_arr)
    return np.concatenate((X, np_arr))

In [152]:
X = np.array([i for i in range(100, 501, 100)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time
S2 = np_transformation(X, 5)
S2

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.87 µs


array([      100,       200,       300,       400,       500, 125000000,
               5,  27000000,         5,   1000000])